services:
  - type: web
    name: south-asia-inequality
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run home.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
